[package]
name = "smt-server"
version = "0.1.0"
edition = "2021"
description = "Reference SMT wire-format server and backends"
license = "MIT OR Apache-2.0"

[dependencies]
binbit = { git = "https://github.com/bint-disasm/binbit" }
dashu = { version = "0.4.2", features = ["num-traits"] }
smt-wire = { path = "../smt-wire" }
yaspar = "2.7.0"
z3 = { version = "0.20.0", features = ["gh-release"] }
